<a href="https://colab.research.google.com/github/Soft-Icon/DataQuest_Challenge/blob/main/10AnalyticsDataQuest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
'''from google.colab import drive
drive.mount('/content/drive')
'''
#This  command keeps failing so drive was mounted manually

"from google.colab import drive\ndrive.mount('/content/drive')\n"

In [3]:
#unzip the file in the drive
!unzip "/content/drive/MyDrive/10Alytics Monthly Knowledge Quest/10ALYTICS_MONTHLY_KNOWLEDGEQUEST.zip" -d /content/

Archive:  /content/drive/MyDrive/10Alytics Monthly Knowledge Quest/10ALYTICS_MONTHLY_KNOWLEDGEQUEST.zip
   creating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/10ALYTICS DATA ANALYTICS MONTHLY QUEST PROJECT DETAILS - JUNE 2025.pptx
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/10ALYTICS DATA SCIENCE MONTHLY QUEST PROJECT DETAILS.pptx
   creating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/customers.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/geolocation.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/leads_closed.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/leads_qualified.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/orders.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/order_items.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/order_payments.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/order_reviews.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/products.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/product_category_name_translation.eCommerce.csv
  inflating: /content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/sellers.eCommerce.csv

In [4]:
dataset_path = "/content/10ALYTICS_MONTHLY_KNOWLEDGEQUEST/e-commerce dataset/"

In [5]:
#import necessary libraries
import pandas as pd
import os

In [6]:
# List of all CSV files to load
csv_files = [
    'customers.eCommerce.csv',
    'geolocation.eCommerce.csv',
    'leads_closed.eCommerce.csv',
    'leads_qualified.eCommerce.csv',
    'order_items.eCommerce.csv',
    'order_payments.eCommerce.csv',
    'order_reviews.eCommerce.csv',
    'orders.eCommerce.csv',
    'product_category_name_translation.eCommerce.csv',
    'products.eCommerce.csv',
    'sellers.eCommerce.csv'
]
# prepare an empty dictionary for use as dataframe
dataframes = {}

In [7]:
#Loading and inspecting datasets
for file in csv_files:
    file_path = os.path.join(dataset_path, file)
    df_name = file.replace('.eCommerce.csv', '')
    try:
        df = pd.read_csv(file_path)
        dataframes[df_name] = df
        print(f'\n--- {df_name} ---')
        print(f'Shape: {df.shape}')
        print(f'Columns: {df.columns.tolist()}')
        print('\nHead:')
        print(df.head())
        print('\nInfo:')
        df.info()
    except Exception as e:
        print(f'Error loading {file}: {e}')

--- customers ---
Shape: (99441, 5)
Columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Head:
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

--- geolocation ---
Shape: (1000163, 5)
Columns: ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Head:
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

--- leads_closed ---
Shape: (842, 14)
Columns: ['mql_id', 'seller_id', 'sdr_id', 'sr_id', 'won_date', 'business_segment', 'lead_type', 'lead_behaviour_profile', 'has_company', 'has_gtin', 'average_stock', 'business_type', 'declared_product_catalog_size', 'declared_monthly_revenue']

Head:
                             mql_id                         seller_id  \
0  5420aad7fec3549a85876ba1c529bd84  2c43fb513632d29b3b58df74816f1b06
1  a555fb36b9368110ede0f043dfc3b9a0  bbb7d7893a450660432ea6652310ebb7
2  327174d3648a2d047e8940d7d15204ca  612170e34b97004b3ba37eae81836b4c
3  f5fee8f7da74f4887f5bcae2bafb6dd6  21e1781e36faf92725dde4730a88ca0f
4  ffe640179b554e295c167a2f6be528e0  ed8cb7b190ceb6067227478e48cf8dde

                             sdr_id                             sr_id  \
0  a8387c01a09e99ce014107505b92388c  4ef15afb4b2723d8f3d81e51ec7afefe
1  09285259593c61296eef10c734121d5b  d3d1e91a157ea7f90548eef82f1955e3
2  b90f87164b5f8c2cfa5c8572834dbe3f  6565aa9ce3178a5caf6171827af3a9ba
3  56bf83c4bb35763a51c2baab501b4c67  d3d1e91a157ea7f90548eef82f1955e3
4  4b339f9567d060bcea4f5136b9f5949e  d3d1e91a157ea7f90548eef82f1955e3

          won_date business_segment      lead_type lead_behaviour_profile  \
0  2/26/2018 19:58              pet  online_medium                    cat
1   5/8/2018 20:17  car_accessories       industry                  eagle
2   6/5/2018 17:27  home_appliances     online_big                    cat
3  1/17/2018 13:51       food_drink   online_small                    NaN
4   7/3/2018 20:17  home_appliances       industry                   wolf

   has_company  has_gtin average_stock business_type  \
0          NaN       NaN           NaN      reseller
1          NaN       NaN           NaN      reseller
2          NaN       NaN           NaN      reseller
3          NaN       NaN           NaN      reseller
4          NaN       NaN           NaN  manufacturer

   declared_product_catalog_size  declared_monthly_revenue
0                            NaN                         0
1                            NaN                         0
2                            NaN                         0
3                            NaN                         0
4                            NaN                         0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842 entries, 0 to 841
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   mql_id                         842 non-null    object
 1   seller_id                      842 non-null    object
 2   sdr_id                         842 non-null    object
 3   sr_id                          842 non-null    object
 4   won_date                       842 non-null    object
 5   business_segment               841 non-null    object
 6   lead_type                      836 non-null    object
 7   lead_behaviour_profile         665 non-null    object
 8   has_company                    63 non-null     float64
 9   has_gtin                       64 non-null     float64
 10  average_stock                  66 non-null     object
 11  business_type                  832 non-null    object
 12  declared_product_catalog_size  69 non-null     float64
 13  declared_monthly_revenue       842 non-null    int64
dtypes: float64(3), int64(1), object(10)
memory usage: 92.2+ KB

--- leads_qualified ---
Shape: (8000, 4)
Columns: ['mql_id', 'first_contact_date', 'landing_page_id', 'origin']

Head:
                             mql_id first_contact_date  \
0  dac32acd4db4c29c230538b72f8dd87d           2/1/2018
1  8c18d1de7f67e60dbd64e3c07d7e9d5d         10/20/2017
2  b4bc852d233dfefc5131f593b538befa          3/22/2018
3  6be030b81c75970747525b843c1ef4f8          1/22/2018
4  5420aad7fec3549a85876ba1c529bd84          2/21/2018

                    landing_page_id          origin
0  88740e65d5d6b056e0cda098e1ea6313          social
1  007f9098284a86ee80ddeb25d53e0af8     paid_search
2  a7982125ff7aa3b2054c6e44f9d28522  organic_search
3  d45d558f0daeecf3cccdffe3c59684aa           email
4  b48ec5f3b04e9068441002a19df93c6c  organic_search

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mql_id              8000 non-null   object
 1   first_contact_date  8000 non-null   object
 2   landing_page_id     8000 non-null   object
 3   origin              7940 non-null   object
dtypes: object(4)
memory usage: 250.1+ KB

--- order_items ---
Shape: (112650, 7)
Columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Head:
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

  shipping_limit_date   price  freight_value
0      9/19/2017 9:45   58.90          13.29
1      5/3/2017 11:05  239.90          19.93
2     1/18/2018 14:48  199.00          17.87
3     8/15/2018 10:10   12.99          12.79
4     2/13/2017 13:57  199.90          18.14

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

--- order_payments ---
Shape: (103886, 5)
Columns: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Head:
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

--- order_reviews ---
Shape: (104719, 7)
Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Head:
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

  review_score review_comment_title  \
0            4                  NaN
1            5                  NaN
2            5                  NaN
3            5                  NaN
4            5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN       1/18/2018 0:00
1                                                NaN       3/10/2018 0:00
2                                                NaN       2/17/2018 0:00
3              Recebi bem antes do prazo estipulado.       4/21/2017 0:00
4  ParabÃ©ns lojas lannister adorei comprar pela ...        3/1/2018 0:00

  review_answer_timestamp
0         1/18/2018 21:46
1          3/11/2018 3:05
2         2/18/2018 14:36
3         4/21/2017 22:02
4          3/2/2018 10:26

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104719 entries, 0 to 104718
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                104163 non-null  object
 1   order_id                 101926 non-null  object
 2   review_score             101781 non-null  object
 3   review_comment_title     12005 non-null   object
 4   review_comment_message   41045 non-null   object
 5   review_creation_date     95396 non-null   object
 6   review_answer_timestamp  95378 non-null   object
dtypes: object(7)
memory usage: 5.6+ MB

--- orders ---
Shape: (99441, 8)
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Head:
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp order_approved_at  \
0    delivered          10/2/2017 10:56   10/2/2017 11:07
1    delivered          7/24/2018 20:41    7/26/2018 3:24
2    delivered            8/8/2018 8:38     8/8/2018 8:55
3    delivered         11/18/2017 19:28  11/18/2017 19:45
4    delivered          2/13/2018 21:18   2/13/2018 22:20

  order_delivered_carrier_date order_delivered_customer_date  \
0              10/4/2017 19:55              10/10/2017 21:25
1              7/26/2018 14:31                8/7/2018 15:27
2               8/8/2018 13:50               8/17/2018 18:06
3             11/22/2017 13:39                12/2/2017 0:28
4              2/14/2018 19:46               2/16/2018 18:17

  order_estimated_delivery_date
0               10/18/2017 0:00
1                8/13/2018 0:00
2                 9/4/2018 0:00
3               12/15/2017 0:00
4                2/26/2018 0:00

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

--- product_category_name_translation ---
Shape: (71, 2)
Columns: ['product_category_name', 'product_category_name_english']

Head:
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

--- products ---
Shape: (32951, 9)
Columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Head:
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

--- sellers ---
Shape: (3095, 4)
Columns: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Head:
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

## Data Cleaning

In [8]:
#customers.eCommerce.csv
customers_df = dataframes["customers"]

#No obvious missing values or type issues from initial inspection, but then check for duplicates
customers_df.drop_duplicates(inplace=True)
print(f"customers_df cleaned. New shape: {customers_df.shape}")

customers_df cleaned. New shape: (99441, 5)

In [9]:
#geolocation.eCommerce.csv
geolocation_df = dataframes["geolocation"]

# Drop duplicates, especially important for location data
geolocation_df.drop_duplicates(inplace=True)
print(f"geolocation_df cleaned. New shape: {geolocation_df.shape}")

geolocation_df cleaned. New shape: (738327, 5)

In [10]:
#leads_closed.eCommerce.csv
leads_closed_df = dataframes["leads_closed"]

# The Correct column name for leads_closed_df is 'won_date'
if 'won_date' in leads_closed_df.columns:
    leads_closed_df["won_date"] = pd.to_datetime(leads_closed_df["won_date"])
else:
    print("Warning: 'won_date' column not found in leads_closed_df.")

leads_closed_df.drop_duplicates(inplace=True)
print(f"leads_closed_df cleaned. New shape: {leads_closed_df.shape}")

leads_closed_df cleaned. New shape: (842, 14)

In [11]:
#leads_qualified.eCommerce.csv
leads_qualified_df = dataframes["leads_qualified"]

# parse date correctly for column named 'first_contact_date'
leads_qualified_df["first_contact_date"] = pd.to_datetime(leads_qualified_df["first_contact_date"])
leads_qualified_df.drop_duplicates(inplace=True)
print(f"leads_qualified_df cleaned. New shape: {leads_qualified_df.shape}")

leads_qualified_df cleaned. New shape: (8000, 4)

In [12]:
# order_items.eCommerce.csv
order_items_df = dataframes["order_items"]

# Check for missing values and duplicates
order_items_df.dropna(inplace=True) # Drop rows with any missing values
order_items_df.drop_duplicates(inplace=True)
print(f"order_items_df cleaned. New shape: {order_items_df.shape}")

order_items_df cleaned. New shape: (112650, 7)

In [13]:
# order_payments.eCommerce.csv
order_payments_df = dataframes["order_payments"]

# Check for missing values and duplicates
order_payments_df.dropna(inplace=True)
order_payments_df.drop_duplicates(inplace=True)
print(f"order_payments_df cleaned. New shape: {order_payments_df.shape}")

order_payments_df cleaned. New shape: (103886, 5)

In [14]:
# order_reviews.eCommerce.csv ---
order_reviews_df = dataframes["order_reviews"]

# Convert timestamp columns to datetime
order_reviews_df["review_creation_date"] = pd.to_datetime(order_reviews_df["review_creation_date"], errors='coerce')
order_reviews_df["review_answer_timestamp"] = pd.to_datetime(order_reviews_df["review_answer_timestamp"], errors='coerce')

# Fill missing review_comment_title and review_comment_message with empty string
order_reviews_df["review_comment_title"].fillna("", inplace=True)
order_reviews_df["review_comment_message"].fillna("", inplace=True)
order_reviews_df.dropna(subset=["review_score"], inplace=True) # Drop rows where review_score is missing
order_reviews_df.drop_duplicates(inplace=True)
print(f"order_reviews_df cleaned. New shape: {order_reviews_df.shape}")

<ipython-input-14-2308644482>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  order_reviews_df["review_comment_title"].fillna("", inplace=True)
<ipython-input-14-2308644482>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  order_reviews_df["review_comment_message"].fillna("", inplace=True)

order_reviews_df cleaned. New shape: (101752, 7)

In [15]:
#orders.eCommerce.csv
orders_df = dataframes["orders"]

# Convert timestamp columns to datetime
for col in ["order_purchase_timestamp", "order_approved_at", "order_delivered_carrier_date",
            "order_delivered_customer_date", "order_estimated_delivery_date"]:
    orders_df[col] = pd.to_datetime(orders_df[col], errors='coerce') # Coerce errors will turn unparseable dates into NaT

# Drop rows where critical timestamps are missing (e.g., purchase timestamp)
orders_df.dropna(subset=["order_purchase_timestamp"], inplace=True)
orders_df.drop_duplicates(inplace=True)
print(f"orders_df cleaned. New shape: {orders_df.shape}")

orders_df cleaned. New shape: (99441, 8)

In [16]:
#product_category_name_translation.eCommerce.csv
product_category_translation_df = dataframes["product_category_name_translation"]
product_category_translation_df.drop_duplicates(inplace=True)
print(f"product_category_translation_df cleaned. New shape: {product_category_translation_df.shape}")

product_category_translation_df cleaned. New shape: (71, 2)

In [17]:
# products.eCommerce.csv
products_df = dataframes["products"]

# Fill missing product_category_name with \'unknown\'
products_df["product_category_name"].fillna("unknown", inplace=True)

# Fill missing numerical product attributes with 0 or median, depending on context. assume, 0.
for col in ["product_name_lenght", "product_description_lenght", "product_photos_qty", "product_weight_g", "product_length_cm", "product_height_cm", "product_width_cm"]:
    products_df[col].fillna(0, inplace=True)
products_df.drop_duplicates(inplace=True)
print(f"products_df cleaned. New shape: {products_df.shape}")

products_df cleaned. New shape: (32951, 9)

<ipython-input-17-3330035810>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df["product_category_name"].fillna("unknown", inplace=True)
<ipython-input-17-3330035810>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df[col].fillna(0, inplace=True)

In [18]:
# sellers.eCommerce.csv
sellers_df = dataframes["sellers"]
sellers_df.drop_duplicates(inplace=True)
print(f"sellers_df cleaned. New shape: {sellers_df.shape}")

# Save cleaned dataframes to a new dictionary
cleaned_dataframes = {
    "customers": customers_df,
    "geolocation": geolocation_df,
    "leads_closed": leads_closed_df,
    "leads_qualified": leads_qualified_df,
    "order_items": order_items_df,
    "order_payments": order_payments_df,
    "order_reviews": order_reviews_df,
    "orders": orders_df,
    "product_category_name_translation": product_category_translation_df,
    "products": products_df,
    "sellers": sellers_df
}

sellers_df cleaned. New shape: (3095, 4)

## Data Integration and Feature Engineering

*Integration for customer insights*

In [19]:
# Merge orders with customers
customers_df2 = cleaned_dataframes['customers']
orders_df2 = cleaned_dataframes['orders']
customers_orders_df = pd.merge(customers_df2, orders_df2, on='customer_id', how='left')

customers_orders_df.head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:00,2017-05-16 15:22:00,2017-05-23 10:47:00,2017-05-25 10:35:00,2017-06-05
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:00,2018-01-12 20:58:00,2018-01-15 17:14:00,2018-01-29 12:41:00,2018-02-06
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:00,2018-05-20 16:19:00,2018-06-11 14:31:00,2018-06-14 17:58:00,2018-06-13
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:00,2018-03-13 17:29:00,2018-03-27 23:22:00,2018-03-28 16:04:00,2018-04-10
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:00,2018-07-29 10:10:00,2018-07-30 15:16:00,2018-08-09 20:55:00,2018-08-15

In [20]:
#Merge with order_items and products for product details
order_items_df2 = cleaned_dataframes['order_items']
products_df2 = cleaned_dataframes['products']
product_category_translation_df2 = cleaned_dataframes['product_category_name_translation']
customers_orders_items_products_df = pd.merge(customers_orders_df, order_items_df2, on='order_id', how='left')
customers_orders_items_products_df = pd.merge(customers_orders_items_products_df, products_df2, on='product_id', how='left')
customers_orders_items_products_df = pd.merge(customers_orders_items_products_df, product_category_translation_df2, on='product_category_name', how='left')

# Merge with geolocation for customer city/state
# Note: geolocation_zip_code_prefix might not be unique, so handle carefully (e.g., take first match)
geolocation_df2 = cleaned_dataframes['geolocation']
geolocation_unique_df = geolocation_df2.drop_duplicates(subset=['geolocation_zip_code_prefix'])
customers_orders_items_products_geo_df = pd.merge(customers_orders_items_products_df, geolocation_unique_df, left_on='customer_zip_code_prefix', right_on='geolocation_zip_code_prefix', how='left')

# Feature Engineering for Customer Insights
# Total purchase value per order item
customers_orders_items_products_geo_df['item_total_price'] = customers_orders_items_products_geo_df['price'] + customers_orders_items_products_geo_df['freight_value']

In [21]:
customers_orders_items_products_geo_df.shape

(113425, 33)

*Integration for Sales Performance Analysis*

In [22]:
# Merge orders with order_payments
order_payments_df = cleaned_dataframes['order_payments']
orders_payments_df = pd.merge(orders_df2, order_payments_df, on='order_id', how='left')

# Merge order_items with sellers for seller performance
sellers_df = cleaned_dataframes['sellers']
order_items_sellers_df = pd.merge(order_items_df2, sellers_df, on='seller_id', how='left')

# Merge leads data
leads_qualified_df2 = cleaned_dataframes['leads_qualified']
leads_closed_df2 = cleaned_dataframes['leads_closed']
leads_combined_df = pd.merge(leads_qualified_df2, leads_closed_df2, on='mql_id', how='left')

*Integration for Delivery & Logistics*

In [23]:
# Delivery duration and variance (already handled in orders_df cleaning for datetime conversion)
orders_df2['delivery_duration'] = (orders_df2['order_delivered_customer_date'] - orders_df2['order_purchase_timestamp']).dt.days
orders_df2['delivery_variance'] = (orders_df2['order_delivered_customer_date'] - orders_df2['order_estimated_delivery_date']).dt.days

In [24]:
orders_df2.head(3)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_duration,delivery_variance
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8.0,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,13.0,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,9.0,-18.0

*Integration for Review & Satisfaction Insights*

In [25]:
# Merge order_reviews with orders and order_items
order_reviews_df = cleaned_dataframes['order_reviews']
order_reviews_orders_df = pd.merge(order_reviews_df, orders_df2, on='order_id', how='left')
order_reviews_orders_items_df = pd.merge(order_reviews_orders_df, order_items_df2, on='order_id', how='left')
order_reviews_orders_items_products_df = pd.merge(order_reviews_orders_items_df, products_df2, on='product_id', how='left')
order_reviews_orders_items_products_df = pd.merge(order_reviews_orders_items_products_df, product_category_translation_df2, on='product_category_name', how='left')
order_reviews_orders_items_products_sellers_df = pd.merge(order_reviews_orders_items_products_df, sellers_df, on='seller_id', how='left')

## Save all processed csv for further analysis

In [26]:
output_dir = "/content/drive/MyDrive/processed_data/"
os.makedirs(output_dir, exist_ok=True)

customers_orders_items_products_geo_df.to_csv(os.path.join(output_dir, "processed_customer_product_geo_data.csv"), index=False)
orders_payments_df.to_csv(os.path.join(output_dir, "processed_orders_payments_data.csv"), index=False)
leads_combined_df.to_csv(os.path.join(output_dir, "processed_leads_data.csv"), index=False)
orders_df.to_csv(os.path.join(output_dir, "processed_orders_delivery_data.csv"), index=False) # orders_df now has delivery features
order_reviews_orders_items_products_sellers_df.to_csv(os.path.join(output_dir, "processed_reviews_data.csv"), index=False)